forum/urls.py
from django.conf.urls import url, patterns

from . import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>\d+)/$', views.forum, name='forum'),
    url(r'^thread/(?P<pk>\d+)/$', views.thread, name='thread'),
    url(r'^(?P<pk>\d+)/add_thread/$', views.add_thread, name='add_thread'),
    url(r'^thread/(?P<pk>\d+)/add_post/$', views.add_post, name='add_post'),
    url(r'^create_forum/$', views.create_forum, name='create_forum'),
    url(r'^accounts/edit_profile/(?P<pk>\d+)/$', views.edit_profile, name='edit_profile'),
    url(r'^thread/post/(?P<pk>\d+)/comment/$', views.comment, name="comment"),
    url(r'^(?P<pk>\d+)/edit/$', views.edit_forum, name="edit_forum"),
    url(r'^thread/(?P<pk>\d+)/edit/$', views.edit_thread, name="edit_thread"),
    url(r'^thread/post/(?P<pk>\d+)/edit/$', views.edit_post, name="edit_post"),
    url(r'^thread/post/comment/(?P<pk>\d+)/edit/$', views.edit_comment, name="edit_comment"),
)

my_forum/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from registration.backends.simple.views import RegistrationView


class MyRegView(RegistrationView):

    def get_success_url(self, request, user):
        return '/forum/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'my_forum.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', include('forum.urls')),  # No namespace here.
    url(r'^forum/', include('forum.urls', namespace='forum')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/register/$', MyRegView.as_view(), name='registration_register'),
    (r'^accounts/', include('registration.backends.simple.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
            'serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

forum/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.


class Forum(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(User, blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)

    def num_posts(self):
        return sum([thread.num_posts() for thread in self.thread_set.all()])

    def num_threads(self):
        return self.thread_set.count()

    def last_post(self):
        if self.thread_set.count():
            last = None
            for thread in self.thread_set.all():
                l = thread.last_post()
                if l:
                    if not last:
                        last = l
                    elif l.created > last.created:
                        last = l
            return last

    def __str__(self):
        return self.title


class Thread(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(User, blank=True, null=True)
    forum = models.ForeignKey(Forum)
    description = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return str(self.creator) + " - " + self.title

    def num_posts(self):
        return self.post_set.count()

    def num_replies(self):
        return self.post_set.count()

    def last_post(self):
        if self.post_set.count():
            return self.post_set.order_by('-created')[0]


class Post(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(User, blank=True, null=True)
    thread = models.ForeignKey(Thread)
    body = models.TextField(max_length=10000)

    def __str__(self):
        return "{} - {} - {}".format(self.creator, self.thread, self.title)

    def short(self):
        return "{} - {}".format(self.creator, self.title)
    short.allow_tags = True


class Comment(models.Model):
    title = models.CharField(max_length=60)
    body = models.TextField(max_length=10000)
    post = models.ForeignKey(Post)
    created = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(User)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    avatar = models.ImageField(upload_to='profile_images', blank=True, null=True)
    posts = models.IntegerField(default=0)
    thumbnail1 = models.ImageField(upload_to='profile_images/thumbs/', blank=True, null=True)
    thumbnail2 = models.ImageField(upload_to='profile_images/thumbs/', blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_thumb_one(self):
        # Have to check if user.userprofile.avatar in template lest avatar be empty and the link reads /media/None
        return str(settings.MEDIA_URL + (
            self.thumbnail1.name if self.thumbnail1.name else self.avatar.name))

    def get_thumb_two(self):
        return str(settings.MEDIA_URL + (
            self.thumbnail2.name if self.thumbnail2.name else self.avatar.name))

    def get_avatar(self):
        return str(settings.MEDIA_URL + self.avatar.name)

forum/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Post, Forum, Thread, UserProfile, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'body')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('title', 'body')


class ThreadForm(forms.ModelForm):

    class Meta:
        model = Thread
        fields = ('title', 'description')


class ForumForm(forms.ModelForm):

    class Meta:
        model = Forum
        fields = ('title', 'description')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('avatar',)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

forum/views.py
import os
from os.path import join as pjoin

from PIL import Image

from django.http import Http404, HttpResponseRedirect
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, InvalidPage, EmptyPage


from .models import Forum, Thread, Post, UserProfile, Comment
from .forms import PostForm, ThreadForm, ForumForm, UserProfileForm, CommentForm
# Create your views here.


def index(request):
    forums = Forum.objects.order_by('-created')
    forums = make_paginator(request, forums, 20)

    context_dict = {'forums': forums}
    return render(request, 'forum/index.html', context_dict)


def forum(request, pk):
    """
    Listing all threads in a forum with pk=pk.
    """
    forum = get_object_or_404(Forum, pk=pk)
    threads = Thread.objects.filter(forum=pk).order_by('-created')
    threads = make_paginator(request, threads, 20)
    context_dict = {'threads': threads, 'forum': forum}
    return render(request, 'forum/forum.html', context_dict)


def thread(request, pk):
    """
    List posts in this thread.
    """
    # get_object_or_404 ?? get_list_or_404?? Or just no error handling at all here???
    try:
        posts = Post.objects.filter(thread=pk).order_by('created')
    except:
        raise Http404

    posts = make_paginator(request, posts, 15)
    thread = get_object_or_404(Thread, pk=pk)

    # Get all comments associated with posts in this thread.
    comments = [com for com in Comment.objects.all() if com.post.thread.pk == thread.pk]
    context_dict = {'posts': posts, 'thread': thread, 'comments': comments}
    return render(request, 'forum/thread.html', context_dict)


def make_paginator(request, items, number):
    '''
    Make a paginator of number items of type 'item'
    '''
    paginator = Paginator(items, number)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    try:
        items = paginator.page(page)
    except(InvalidPage, EmptyPage):
        items = paginator.page(paginator.num_pages)

    return items


@login_required
def add_thread(request, pk):
    forum = get_object_or_404(Forum, pk=pk)
    if request.method == 'POST':
        thread = Thread(forum=forum)
        form = ThreadForm(request.POST, instance=thread)
        if form.is_valid():
            thread = form.save(commit=False)
            thread.creator = request.user
            thread.save()
            return redirect('forum:forum', pk=pk)
    else:
        form = ThreadForm()

    context_dict = {'form': form, 'forum': forum}
    return render(request, 'forum/add_thread.html', context_dict)


@login_required
def edit_thread(request, pk):
    thread = get_object_or_404(Thread, pk=pk)

    if request.method == 'POST':
        form = ThreadForm(request.POST, instance=thread)
        if form.is_valid():
            thread = form.save(commit=False)
            thread.creator = request.user
            thread.save()
            return redirect('forum:thread', pk=thread.pk)
    else:
        form = ThreadForm(instance=thread)

    context_dict = {
        'form': form,
        'forum': Forum.objects.get(pk=thread.forum.pk),
        'thread': thread
    }
    return render(request, 'forum/edit_thread.html', context_dict)


@login_required
def add_post(request, pk):
    thread = get_object_or_404(Thread, pk=pk)
    if request.method == 'POST':
        post = Post(thread=thread)
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.creator = request.user
            post.save()

            profile = UserProfile.objects.get(user=post.creator)
            profile.posts += 1
            profile.save()
            return redirect('forum:thread', pk=pk)
        else:
            print(form.errors)
    else:
        form = PostForm()
    context_dict = {'form': form, 'thread': thread}
    return render(request, 'forum/add_post.html', context_dict)


@login_required
def edit_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.creator = request.user
            post.save()
            return redirect('forum:thread', pk=post.thread.pk)
    else:
        form = PostForm(instance=post)
    context_dict = {'form': form, 'post': post}
    return render(request, 'forum/edit_post.html', context_dict)


@login_required
def create_forum(request):
    if not request.user.is_staff:
        return HttpResponseRedirect('/forum/')

    if request.method == 'POST':
        form = ForumForm(request.POST)
        if form.is_valid():
            forum = form.save(commit=False)
            forum.creator = request.user
            forum.save()
            return redirect('forum:index')
        else:
            print(form.errors)
    else:
        form = ForumForm()
    return render(request, 'forum/create_forum.html', {'form': form})


@login_required
def edit_forum(request, pk):
    forum = get_object_or_404(Forum, pk=pk)

    if request.method == 'POST':
        form = ForumForm(request.POST, instance=forum)
        if form.is_valid():
            forum = form.save(commit=False)
            forum.creator = request.user
            forum.save()
            return redirect('forum:forum', pk=pk)
    else:
        form = ForumForm(instance=forum)
    context_dict = {'form': form, 'forum': forum}
    return render(request, 'forum/edit_forum.html', context_dict)


@login_required
def edit_profile(request, pk):
    try:
        profile = UserProfile.objects.get(user=User.objects.get(pk=pk))
    except:
        profile = None

    # Repeated code in if 'avatar' in request.FILES -- should figure out an abstraction
    if request.method == 'POST':
        if profile:
            form = UserProfileForm(request.POST, instance=profile)
            if form.is_valid():
                if 'avatar' in request.FILES:
                    avatar = request.FILES['avatar']
                    if not is_image(avatar.name):
                        info = "Please choose an image file (jpg, png, gif)"
                        context_dict = {'edit_success': False, 'form': form, 'info': info}
                        return render(request, 'forum/edit_profile.html', context_dict)

                    profile.avatar = avatar
                    profile.save()  # Save here, else can't access profile.avatar in the two lines that follow.
                    profile.thumbnail1 = makethumbnail(profile.avatar.name)
                    profile.thumbnail2 = makethumbnail(profile.avatar.name, (300, 300))
                    profile.save()
        else:
            form = UserProfileForm(request.POST)
            if form.is_valid():
                profile = form.save(commit=False)
                profile.user = request.user
                if 'avatar' in request.FILES:
                    avatar = request.FILES['avatar']
                    if not is_image(avatar.name):
                        info = "Please choose an image file (jpg, png, gif)"
                        context_dict = {'edit_success': False, 'form': form, 'info': info}
                        return render(request, 'forum/edit_profile.html', context_dict)
                    profile.avatar = avatar
                    profile.save()
                    profile.thumbnail1 = makethumbnail(profile.avatar.name)
                    profile.thumbnail2 = makethumbnail(profile.avatar.name, (300, 300))
                profile.save()  # Save the user profile, with or without an avatar.
            else:
                print(form.errors)
                context_dict = {'form': form, 'edit_success': False}
                return render(request, 'forum/edit_profile.html', context_dict)

        context_dict = {'form': form, 'edit_success': True}
        # Return this if successfully made or updated the profile.
        return render(request, 'forum/edit_profile.html', context_dict)
    else:
        form = UserProfileForm()
        context_dict = {'form': form, 'get': True}
    return render(request, 'forum/edit_profile.html', context_dict)


def is_image(name):
    if os.path.splitext(name)[1].lower() in ['.jpeg', '.jpg', '.gif', '.png']:
        return True
    return False


def makethumbnail(imgfile, size=(200, 200)):
    thumbsdir = pjoin(settings.MEDIA_ROOT, 'profile_images/thumbs')
    if not os.path.exists(thumbsdir):
        print('Making thumb dir...', thumbsdir)
        os.mkdir(thumbsdir)

    fname, ext = os.path.splitext(imgfile)
    fname = fname.split('/')[1]     # Remove 'profile_images' prefix

    thumbsize = str(size[0]) + 'x' + str(size[1])
    thumbnail = fname + '-thumb-' + thumbsize + ext
    thumbnailfile = pjoin(thumbsdir, thumbnail)

    try:
        thumb = Image.open(pjoin(settings.MEDIA_ROOT, imgfile))
        thumb.thumbnail(size, Image.ANTIALIAS)
        thumb.save(thumbnailfile)
        return 'profile_images/thumbs/' + thumbnail
    except:
        print("Error encountered. Skipping => ", thumbnailfile)
        return False


@login_required
def comment(request, pk):
    post = get_object_or_404(Post, id=pk)

    if request.method == 'POST':
        comment = Comment(post=post)
        comment_form = CommentForm(request.POST, instance=comment)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.creator = request.user
            comment.save()

            return redirect('forum:thread', pk=post.thread_id)
    else:
        comment_form = CommentForm()
    context_dict = {'post': post, 'form': comment_form}
    return render(request, 'forum/add_comment.html', context_dict)


@login_required
def edit_comment(request, pk):

forum/templates/forum/add_comment.html
{% extends "forum/base.html" %}

{% load staticfiles %}

{% block title %}
    | Comment :: {{ post.title }}
{% endblock %}

{% block content %}
    <div class="container row">
        <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3">
            <form action="{% url 'forum:comment' pk=post.pk %}" method="post">
                {% csrf_token %}
                {% if form.errors %}
                    {{ form.errors }}
                {% endif %}
                
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input type="text" class="form-control" id="id_title" placeholder="Title" maxlength="60" name="title">
                </div>

                <div class="form-group">
                    <label for="id_body">Content</label>
                    <textarea class="form-control" rows="5" id="id_body" placeholder="Your Comment." name="body"></textarea>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                
            </form>

            <div class="pull-left" style="clear: both">
                <a href="{% url 'forum:thread' pk=post.thread.pk %}">&laquo; Back to topic.</a>
            </div>
        </div>
    </div>
{% endblock %}

forum/templates/forum/add_post.html
{% extends "forum/base.html" %}
{% load staticfiles %}

{% if thread %}
    {% block title %}
        | Re: {{ thread.title }}
    {% endblock title %}
{% endif %}

{% block content %}
    <br>
    <div class="container row">
        <div class="col-sm-8 col-sm-offset-2">
            <form action="{% url 'forum:add_post' pk=thread.pk %}" method="POST" class="form-horizontal" role="form">
                {% csrf_token %}
                <div class="form-group">
                    <legend><h2>re: {{ thread.title }}</h2></legend>
                </div>

                <div class="form-group">
                    <div class="col-sm-2">
                        <label for="id_title" class="control-label">Post Title: </label>
                    </div>
                    <div class="col-sm-10">
                        <input type="text" id="id_title" name="title" maxlength="60" class="form-control" placeholder="Title">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-2">
                        <label for="id_body" class="control-label">Post Content: </label>
                    </div>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="id_body" cols="40" rows="10" maxlength="10000" name="body" placeholder="Reply..."></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-2">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="pull-left">
        <a href="{% url 'forum:thread' pk=thread.pk %}">&laquo; Back to topic.</a>
    </div>
{% endblock content %}

forum/templates/forum/add_thread.html
{% extends "forum/base.html" %}
{% load staticfiles %}

{% if forum %}
    {% block title %}
        | Adding a thread to: {{ forum.title }}
    {% endblock title %}
{% endif %}

{% block content %}
    <div class="container col-md-10 col-md-offset-1">
        <form role="form" action="{% url 'forum:add_thread' pk=forum.pk %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <legend>Start a topic in {{ forum.title }}</legend>
            </div>
            <div class="form-group">
                <label for="id_title">Subject</label>
                {% if form.errors %}
                    <div class="alert alert-danger">
                        <p>This field is required.</p>
                    </div>
                {% endif %}
                <input type="text" id="id_title" maxlength="60" name="title" class="form-control">
            </div>

             <div class="form-group">
                <label for="id_description">Description</label>
                <textarea class="form-control" maxlength="255" rows="3" id="id_description" name="description" placeholder="A short description of the topic"></textarea>
            </div>

            <div class="form-group">
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </form>
        <div class="row" style="clear: both">
            <div class="pull-left">
                <a href="{% url 'forum:forum' pk=forum.pk %}">&laquo; Back to forum.</a>
            </div>
        </div>
    </div>
{% endblock content %}

forum/templates/forum/create_forum.html
{% extends "forum/base.html" %}
{% load staticfiles %}

{% block title %}
    | Create Forum
{% endblock title %}

{% block content %}
    <div class="container">
        <br>
        <form role="form" method="post" action="{% url 'forum:create_forum' %}">
            {% csrf_token %}
            <div class="form-group">
                <legend>Create Forum</legend>
            </div>
            <div class="form-group">
                <label for="id_title">Title</label>
                <input class="form-control" id="id_title" name="title" maxlength="60" type="text" placeholder="Title">
            </div>

            <div class="form-group">
                <label for="id_description">Description</label>
                <textarea class="form-control" maxlength="255" rows="3" id="id_description" name="description" placeholder="A short description of the forum"></textarea>
            </div>

            <div class="form-group">
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </form>

        <div class="pull-left" style="clear: both">
            <a href="{% url 'forum:index' %}">&laquo; Back to forums.</a>
        </div>
    </div>
{% endblock content %}

forum/templates/forum/edit_comment.html
{% extends "forum/base.html" %}
{% load staticfiles %}

{% if comment %}
    {% block title %}
        | Editing {{ comment.title }}
    {% endblock title %}
{% endif %}

{% block content %}
    <div class="container col-md-10 col-md-offset-1">
        <form role="form" action="{% url 'forum:edit_comment' pk=comment.pk %}" method="post" id="form-content" class="compost">
            {% csrf_token %}
            {{ form.as_p }}
        </form>
        <div class="row" style="clear: both">
            <div class="pull-left">
                <a href="{% url 'forum:thread' pk=comment.post.thread_id %}">&laquo; Back to topic.</a>
            </div>
        </div>
    </div>
{% endblock content %}

forum/templates/forum/edit_forum.html
{% extends "forum/base.html" %}
{% load staticfiles %}

{% block title %}
    | Editing {{ forum.title }}
{% endblock title %}

{% block content %}
    <div class="container col-md-8 col-md-offset-2">
        <br>
        <form role="form" method="post" action="{% url 'forum:edit_forum' pk=forum.pk %}" id="form-content" class="threadforum">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>

        <div class="pull-left" style="clear: both">
            <a href="{% url 'forum:index' %}">&laquo; Back to forums.</a>
        </div>
    </div>
{% endblock content %}

forum/templates/forum/edit_post.html
{% extends "forum/base.html" %}
{% load staticfiles %}

{% if post %}
    {% block title %}
        | Editing {{ post.title }}
    {% endblock title %}
{% endif %}

{% block content %}
    <div class="container col-md-10 col-md-offset-1">
        <form role="form" action="{% url 'forum:edit_post' pk=post.pk %}" method="post" id="form-content" class="compost">
            {% csrf_token %}
            {{ form.as_p }}
        </form>
        <div class="row" style="clear: both">
            <div class="pull-left">
                <a href="{% url 'forum:thread' pk=post.thread_id %}">&laquo; Back to topic.</a>
            </div>
        </div>
    </div>
{% endblock content %}

forum/templates/forum/thread.html
{% extends "forum/base.html" %}

{% load staticfiles %}

{% if thread %}
    {% block title %}
        | {{ thread.title }}
    {% endblock title %}
{% endif %}

{% block content %}
    <div class="container">
        {% if thread %}
            <div class="page-header">
                <h1 class="content-title">
                    <span id="thread-title">{{ thread.title }}</span>
                    {% if thread.description %}
                        <br>
                        <span id="thread-description"><small>{{ thread.description }}</small></span>
                    {% else %}
                        <br>
                        <small><em>No description available.</em></small>
                    {% endif %}
                </h1>
                <div>
                    <small>Created by: {{ thread.creator }}</small> <br>
                    <small>Created On: {{ thread.created }}</small>
                </div>
                <br>
                {% if user.is_authenticated %}
                    <div class="pull-right">
                        <a href="{% url 'forum:add_post' pk=thread.pk %}" class="pull-right btn btn-primary start-new-btn">New Post</a>
                    </div>
                {% endif %}

                {% if thread.creator == user and user.is_authenticated %}
                    <span><a href="{% url 'forum:edit_thread' pk=thread.pk %}" class="btn btn-link" id="editThread">Edit thread name and description</a></span>                
                {% endif %}
            </div>
        {% endif %}
        <div class="col-xs-12 col-md-10 col-md-offset-1">
            {% if posts %}
                {% for post in posts %}
                    <div class="media post">
                        <a class="pull-left">
                            {% if post.creator.userprofile.avatar %}
                                <img src="{{ post.creator.userprofile.get_thumb_one }}" height="100" width="150" alt="{{ post.creator }}">
                                <div>{{ post.creator }}<br>{{ post.created }}<br>Posts: {{ post.creator.userprofile.posts }}</div>
                            {% else %}
                                <span class="glyphicon glyphicon-user"></span>
                            {% endif %}
                        </a>
                        <div class="media-body">
                            <h3 class="media-heading content-title">{{ post.title }}</h3>
                            <p>
                                {{ post.body | linebreaks }}
                            </p>
                            <div>
                                {% if user == post.creator and user.is_authenticated %}
                                    <span><a href="{% url 'forum:edit_post' pk=post.pk %}">Edit</a></span>
                                {% endif %}
                                <span>
                                    <a href="{% url 'forum:comment' pk=post.pk %}" class="btn btn-link">Reply</a>
                                </span>
                            </div>

                            {% if comments %}
                                <hr>
                                <h4 class="page-header content-title">Comments</h4>
                                {% for comment in comments %}
                                    {% if comment.post.pk == post.pk %}
                                        <div class="comment">
                                            <div class="media">
                                                <a class="pull-left">
                                                    {% if comment.creator.userprofile.avatar %}
                                                        <img src="{{ comment.creator.userprofile.get_thumb_one }}" height="75" width="100" alt="{{ comment.creator }}">
                                                        <div>{{ comment.creator }}<br>{{ comment.created }}</div>
                                                    {% else %}
                                                        <span class="glyphicon glyphicon-user"></span>
                                                    {% endif %}
                                                </a>
                                                <div class="media-body">
                                                    <h4 class="media-heading content-title">{{ comment.title }}</h4>
                                                    <p>{{ comment.body | linebreaks }}</p>
                                                    {% if user == comment.creator %}
                                                        <br>
                                                        <span><a href="{% url 'forum:edit_comment' pk=comment.pk %}" class="btn btn-link">Edit</a></span>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="well well-lg">
                    <h3>No posts about this yet.</h3>
                    {% if user.is_authenticated %}
                        <p>You can post something <a href="{% url 'forum:add_post' pk=thread.pk %}">here.</a></p>
                        
                    {% endif %}
                </div>
            {% endif %}
            <div class="pull-left" style="clear: both">
                <a href="{% url 'forum:forum' pk=thread.forum.pk %}">&laquo; Back to thread.</a>
            </div>
        </div>
    </div>
    {% if posts %}
        <div class="row" style="clear: both">
            <span class="step-links">
                <ul class="pager">
                    <div class="col-xs-4">
                        {% if posts.has_previous %}
                            <li class="previous">
                                <a href="?page={{ posts.previous_page_number }}">&larr; Newer</a>
                            </li>
                        {% endif %}
                    </div>
                    <div class="col-xs-4">
                        <li class="active">
                            <a href="#">{{ posts.number }} / {{ posts.paginator.num_pages }}</a>
                        </li>
                    </div>
                    <div class="col-xs-4">
                        {% if posts.has_next %}
                            <li class="next">
                                <a href="?page={{ posts.next_page_number }}">Older &rarr;</a>
                            </li>
                        {% endif %}
                    </div>
                </ul>
            </span>
        </div>
    {% endif %}

{% endblock content %}